name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Api
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          
      - name: Run Deployment Script
        run: |
          cd /srv/apps
          git clone git@github.com:brayohmurithidev/employee-management-system.git
          echo 'Deployment successful'
